# Generated by Django 4.0.6 on 2022-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('full', 'Полный доступ'), ('free', 'Только бесплатные')], default='free', max_length=30),
        ),
    ]
